import type React from "react";
import { createContext, useContext, useEffect, useState } from "react";

export type Language = "tr" | "en" | "de" | "fr" | "es" | "ar" | "ru" | "zh";

const translations: Record<Language, Record<string, string>> = {
  tr: {
    "landing.title": "ERPVerse",
    "landing.subtitle": "Birleşik İş Yönetim Platformu",
    "landing.description": "Şirketinizi tek platformdan yönetin",
    "portal.owner": "Şirket Sahibi",
    "portal.owner.desc": "Şirketi kur veya yönet",
    "portal.manager": "Şirket Yöneticisi",
    "portal.manager.desc": "Yönetici paneline giriş",
    "portal.admin": "Şirket İdarecisi",
    "portal.admin.desc": "İdareci paneline giriş",
    "portal.employee": "Şirket Personeli",
    "portal.employee.desc": "Personel paneline giriş",
    "auth.login": "Giriş Yap",
    "auth.register": "Kayıt Ol",
    "auth.loginCode": "Giriş Kodunuz",
    "auth.personnelCode": "Personel Kodunuz",
    "auth.fullName": "Ad Soyad",
    "auth.enterCode": "Kodunuzu girin",
    "auth.enterName": "Adınızı girin",
    "auth.submit": "Devam Et",
    "auth.backToLogin": "Giriş Yap",
    "auth.noCompany":
      "Henüz bir şirkete dahil değilsiniz. Şirket yöneticinizle iletişime geçin.",
    "code.title": "Kayıt Başarılı!",
    "code.subtitle":
      "Aşağıdaki kodları güvenli bir yere kaydedin. Tekrar gösterilmeyecek!",
    "code.loginCode": "Giriş Kodunuz",
    "code.personnelCode": "Personel Kodunuz",
    "code.copied": "Kopyalandı!",
    "code.copy": "Kopyala",
    "code.continue": "Giriş Yap",
    "company.setup.title": "Şirket Kurulumu",
    "company.setup.subtitle": "Şirketinizin bilgilerini girin",
    "company.name": "Şirket Adı",
    "company.sector": "Sektör",
    "company.address": "Adres",
    "company.email": "İletişim E-postası",
    "company.phone": "Telefon",
    "company.foundedYear": "Kuruluş Yılı",
    "company.create": "Şirketi Kur",
    "company.select.title": "Şirket Seçin",
    "company.select.subtitle": "Hangi şirkete giriş yapmak istiyorsunuz?",
    "dashboard.overview": "Genel Bakış",
    "dashboard.personnel": "Personel Yönetimi",
    "dashboard.modules": "Modül İzinleri",
    "dashboard.settings": "Ayarlar",
    "dashboard.employees": "Toplam Personel",
    "dashboard.activeModules": "Aktif Modül",
    "dashboard.company": "Şirket",
    "personnel.add": "Personel Ekle",
    "personnel.code": "Personel Kodu",
    "personnel.role": "Rol",
    "personnel.modules": "Modüller",
    "personnel.remove": "Çıkar",
    "personnel.added": "Personel başarıyla eklendi",
    "personnel.removed": "Personel çıkarıldı",
    "personnel.notFound": "Personel bulunamadı",
    "personnel.noMembers": "Henüz personel eklenmedi",
    "role.owner": "Şirket Sahibi",
    "role.manager": "Şirket Yöneticisi",
    "role.admin": "Şirket İdarecisi",
    "role.employee": "Şirket Personeli",
    "modules.HR": "İnsan Kaynakları",
    "modules.Accounting": "Muhasebe",
    "modules.CRM": "CRM",
    "modules.Inventory": "Stok",
    "modules.Projects": "Projeler",
    "modules.Purchasing": "Satın Alma",
    "modules.Production": "Üretim",
    "modules.Workflow": "İş Akışı",
    "modules.Reporting": "Raporlama",
    "nav.logout": "Çıkış",
    "nav.back": "Geri",
    "common.save": "Kaydet",
    "common.cancel": "İptal",
    "common.loading": "Yükleniyor...",
    "common.error": "Hata oluştu",
    "common.success": "Başarılı",
    "module.comingSoon": "Bu modül yakında aktif olacak",
    "purchasing.title": "Satın Alma",
    "purchasing.supplier": "Tedarikçi",
    "purchasing.amount": "Tutar",
    "purchasing.date": "Tarih",
    "purchasing.status": "Durum",
    "purchasing.addOrder": "Sipariş Ekle",
    "purchasing.pending": "Bekliyor",
    "purchasing.approved": "Onaylandı",
    "purchasing.delivered": "Teslim Edildi",
    "purchasing.totalOrders": "Toplam Sipariş",
    "production.title": "Üretim",
    "production.product": "Ürün",
    "production.quantity": "Miktar",
    "production.progress": "İlerleme",
    "production.status": "Durum",
    "production.addOrder": "Üretim Ekle",
    "production.planned": "Planlandı",
    "production.inProgress": "Devam Ediyor",
    "production.completed": "Tamamlandı",
    "workflow.title": "İş Akışı",
    "workflow.task": "Görev",
    "workflow.assignee": "Atanan",
    "workflow.priority": "Öncelik",
    "workflow.status": "Durum",
    "workflow.addTask": "Görev Ekle",
    "workflow.high": "Yüksek",
    "workflow.medium": "Orta",
    "workflow.low": "Düşük",
    "workflow.pending": "Bekliyor",
    "workflow.inProgress": "Devam Ediyor",
    "workflow.done": "Tamamlandı",
    "reporting.title": "Raporlama",
    "reporting.revenue": "Gelir",
    "reporting.expenses": "Giderler",
    "reporting.netProfit": "Net Kar",
    "reporting.employees": "Çalışanlar",
    "reporting.monthlyChart": "Aylık Grafik",
    "reporting.moduleUsage": "Modül Kullanımı",
    "reporting.totalEmployees": "Toplam Çalışan",
    "reporting.active": "aktif",
    "reporting.totalTransactions": "Toplam İşlem",
    "reporting.totalCustomers": "Toplam Müşteri",
    "reporting.totalProducts": "Toplam Ürün",
    "reporting.totalProjects": "Toplam Proje",
    "reporting.openOrders": "Açık Siparişler",
    "reporting.productionOrders": "Üretim Siparişleri",
    "reporting.workflowTasks": "İş Akışı Görevleri",
    "reporting.totalRecords": "Toplam Kayıt",
    "reporting.noData": "Henüz veri bulunmuyor",
    "reporting.noDataSub": "Modüllere veri ekleyin, raporlar burada görünecek",
    "reporting.dataSummary": "Modül Veri Özeti",
    "hr.title": "İnsan Kaynakları",
    "hr.employee": "Çalışan",
    "hr.position": "Pozisyon",
    "hr.department": "Departman",
    "hr.status": "Durum",
    "hr.active": "Aktif",
    "hr.onLeave": "İzinli",
    "hr.terminated": "Ayrılmış",
    "hr.addEmployee": "Çalışan Ekle",
    "hr.totalEmployees": "Toplam Çalışan",
    "hr.searchEmployee": "Çalışan ara...",
    "accounting.title": "Muhasebe",
    "accounting.income": "Gelir",
    "accounting.expense": "Gider",
    "accounting.balance": "Net Bakiye",
    "accounting.description": "Açıklama",
    "accounting.amount": "Tutar",
    "accounting.date": "Tarih",
    "accounting.category": "Kategori",
    "accounting.addTransaction": "İşlem Ekle",
    "accounting.type": "Tür",
    "crm.title": "Müşteri İlişkileri",
    "crm.customer": "Müşteri",
    "crm.lead": "Potansiyel",
    "crm.email": "E-posta",
    "crm.phone": "Telefon",
    "crm.status": "Durum",
    "crm.addCustomer": "Müşteri Ekle",
    "crm.lead_status": "Potansiyel",
    "crm.active_status": "Aktif",
    "crm.closed_status": "Kapandı",
    "inventory.title": "Stok Yönetimi",
    "inventory.product": "Ürün",
    "inventory.category": "Kategori",
    "inventory.quantity": "Miktar",
    "inventory.unitPrice": "Birim Fiyat",
    "inventory.totalValue": "Toplam Değer",
    "inventory.addProduct": "Ürün Ekle",
    "inventory.lowStock": "Düşük Stok",
    "projects.title": "Proje Yönetimi",
    "projects.project": "Proje",
    "projects.status": "Durum",
    "projects.startDate": "Başlangıç",
    "projects.endDate": "Bitiş",
    "projects.team": "Kişi",
    "projects.addProject": "Proje Ekle",
    "projects.planning_status": "Planlama",
    "projects.active_status": "Aktif",
    "projects.completed_status": "Tamamlandı",
    "projects.paused_status": "Duraklatıldı",
    "projects.tasks": "Görevler",
    "settings.title": "Şirket Ayarları",
    "supplier.title": "Tedarikçiler",
    "supplier.add": "Tedarikçi Ekle",
    "supplier.edit": "Tedarikçiyi Düzenle",
    "supplier.name": "Tedarikçi Adı",
    "supplier.contact": "İletişim Kişisi",
    "supplier.phone": "Telefon",
    "supplier.email": "E-posta",
    "supplier.category": "Kategori",
    "supplier.paymentTerms": "Ödeme Koşulları",
    "supplier.rating": "Değerlendirme",
    "supplier.notes": "Notlar",
    "supplier.totalSuppliers": "Toplam Tedarikçi",
    "purchasing.tabs.orders": "Siparişler",
    "purchasing.tabs.suppliers": "Tedarikçiler",
    "profile.title": "Profil Ayarları",
    "profile.displayName": "Ad Soyad",
    "profile.loginCode": "Giriş Kodu",
    "profile.personnelCode": "Personel Kodu",
    "profile.language": "Dil Tercihi",
    "profile.save": "Kaydet",
    "profile.saved": "Kaydedildi",
    "profile.show": "Göster",
    "profile.hide": "Gizle",
    "profile.copy": "Kopyala",
    "profile.copied": "Kopyalandı",
    "nav.profile": "Profil",
  },
  en: {
    "landing.title": "ERPVerse",
    "landing.subtitle": "Unified Business Management Platform",
    "landing.description": "Manage your company from a single platform",
    "portal.owner": "Company Owner",
    "portal.owner.desc": "Set up or manage your company",
    "portal.manager": "Company Manager",
    "portal.manager.desc": "Access manager panel",
    "portal.admin": "Company Admin",
    "portal.admin.desc": "Access admin panel",
    "portal.employee": "Company Employee",
    "portal.employee.desc": "Access employee panel",
    "auth.login": "Login",
    "auth.register": "Register",
    "auth.loginCode": "Your Login Code",
    "auth.personnelCode": "Your Personnel Code",
    "auth.fullName": "Full Name",
    "auth.enterCode": "Enter your code",
    "auth.enterName": "Enter your name",
    "auth.submit": "Continue",
    "auth.backToLogin": "Login",
    "auth.noCompany":
      "You are not part of any company yet. Contact your company manager.",
    "code.title": "Registration Successful!",
    "code.subtitle":
      "Save the codes below in a safe place. They will not be shown again!",
    "code.loginCode": "Your Login Code",
    "code.personnelCode": "Your Personnel Code",
    "code.copied": "Copied!",
    "code.copy": "Copy",
    "code.continue": "Login",
    "company.setup.title": "Company Setup",
    "company.setup.subtitle": "Enter your company details",
    "company.name": "Company Name",
    "company.sector": "Sector",
    "company.address": "Address",
    "company.email": "Contact Email",
    "company.phone": "Phone",
    "company.foundedYear": "Founded Year",
    "company.create": "Create Company",
    "company.select.title": "Select Company",
    "company.select.subtitle": "Which company do you want to access?",
    "dashboard.overview": "Overview",
    "dashboard.personnel": "Personnel Management",
    "dashboard.modules": "Module Permissions",
    "dashboard.settings": "Settings",
    "dashboard.employees": "Total Employees",
    "dashboard.activeModules": "Active Modules",
    "dashboard.company": "Company",
    "personnel.add": "Add Personnel",
    "personnel.code": "Personnel Code",
    "personnel.role": "Role",
    "personnel.modules": "Modules",
    "personnel.remove": "Remove",
    "personnel.added": "Personnel added successfully",
    "personnel.removed": "Personnel removed",
    "personnel.notFound": "Personnel not found",
    "personnel.noMembers": "No personnel added yet",
    "role.owner": "Company Owner",
    "role.manager": "Company Manager",
    "role.admin": "Company Admin",
    "role.employee": "Company Employee",
    "modules.HR": "Human Resources",
    "modules.Accounting": "Accounting",
    "modules.CRM": "CRM",
    "modules.Inventory": "Inventory",
    "modules.Projects": "Projects",
    "modules.Purchasing": "Purchasing",
    "modules.Production": "Production",
    "modules.Workflow": "Workflow",
    "modules.Reporting": "Reporting",
    "nav.logout": "Logout",
    "nav.back": "Back",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.success": "Success",
    "module.comingSoon": "This module will be active soon",
    "purchasing.title": "Purchasing",
    "purchasing.supplier": "Supplier",
    "purchasing.amount": "Amount",
    "purchasing.date": "Date",
    "purchasing.status": "Status",
    "purchasing.addOrder": "Add Order",
    "purchasing.pending": "Pending",
    "purchasing.approved": "Approved",
    "purchasing.delivered": "Delivered",
    "purchasing.totalOrders": "Total Orders",
    "production.title": "Production",
    "production.product": "Product",
    "production.quantity": "Quantity",
    "production.progress": "Progress",
    "production.status": "Status",
    "production.addOrder": "Add Production",
    "production.planned": "Planned",
    "production.inProgress": "In Progress",
    "production.completed": "Completed",
    "workflow.title": "Workflow",
    "workflow.task": "Task",
    "workflow.assignee": "Assignee",
    "workflow.priority": "Priority",
    "workflow.status": "Status",
    "workflow.addTask": "Add Task",
    "workflow.high": "High",
    "workflow.medium": "Medium",
    "workflow.low": "Low",
    "workflow.pending": "Pending",
    "workflow.inProgress": "In Progress",
    "workflow.done": "Done",
    "reporting.title": "Reporting",
    "reporting.revenue": "Revenue",
    "reporting.expenses": "Expenses",
    "reporting.netProfit": "Net Profit",
    "reporting.employees": "Employees",
    "reporting.monthlyChart": "Monthly Chart",
    "reporting.moduleUsage": "Module Usage",
    "reporting.totalEmployees": "Total Employees",
    "reporting.active": "active",
    "reporting.totalTransactions": "Total Transactions",
    "reporting.totalCustomers": "Total Customers",
    "reporting.totalProducts": "Total Products",
    "reporting.totalProjects": "Total Projects",
    "reporting.openOrders": "Open Orders",
    "reporting.productionOrders": "Production Orders",
    "reporting.workflowTasks": "Workflow Tasks",
    "reporting.totalRecords": "Total Records",
    "reporting.noData": "No data yet",
    "reporting.noDataSub": "Add data to modules and reports will appear here",
    "reporting.dataSummary": "Module Data Summary",
    "hr.title": "Human Resources",
    "hr.employee": "Employee",
    "hr.position": "Position",
    "hr.department": "Department",
    "hr.status": "Status",
    "hr.active": "Active",
    "hr.onLeave": "On Leave",
    "hr.terminated": "Terminated",
    "hr.addEmployee": "Add Employee",
    "hr.totalEmployees": "Total Employees",
    "hr.searchEmployee": "Search employee...",
    "accounting.title": "Accounting",
    "accounting.income": "Income",
    "accounting.expense": "Expense",
    "accounting.balance": "Net Balance",
    "accounting.description": "Description",
    "accounting.amount": "Amount",
    "accounting.date": "Date",
    "accounting.category": "Category",
    "accounting.addTransaction": "Add Transaction",
    "accounting.type": "Type",
    "crm.title": "Customer Relations",
    "crm.customer": "Customer",
    "crm.lead": "Lead",
    "crm.email": "Email",
    "crm.phone": "Phone",
    "crm.status": "Status",
    "crm.addCustomer": "Add Customer",
    "crm.lead_status": "Lead",
    "crm.active_status": "Active",
    "crm.closed_status": "Closed",
    "inventory.title": "Inventory",
    "inventory.product": "Product",
    "inventory.category": "Category",
    "inventory.quantity": "Quantity",
    "inventory.unitPrice": "Unit Price",
    "inventory.totalValue": "Total Value",
    "inventory.addProduct": "Add Product",
    "inventory.lowStock": "Low Stock",
    "projects.title": "Projects",
    "projects.project": "Project",
    "projects.status": "Status",
    "projects.startDate": "Start Date",
    "projects.endDate": "End Date",
    "projects.team": "Members",
    "projects.addProject": "Add Project",
    "projects.planning_status": "Planning",
    "projects.active_status": "Active",
    "projects.completed_status": "Completed",
    "projects.paused_status": "Paused",
    "projects.tasks": "Tasks",
    "settings.title": "Company Settings",
    "supplier.title": "Suppliers",
    "supplier.add": "Add Supplier",
    "supplier.edit": "Edit Supplier",
    "supplier.name": "Supplier Name",
    "supplier.contact": "Contact Person",
    "supplier.phone": "Phone",
    "supplier.email": "Email",
    "supplier.category": "Category",
    "supplier.paymentTerms": "Payment Terms",
    "supplier.rating": "Rating",
    "supplier.notes": "Notes",
    "supplier.totalSuppliers": "Total Suppliers",
    "purchasing.tabs.orders": "Orders",
    "purchasing.tabs.suppliers": "Suppliers",
    "profile.title": "Profile Settings",
    "profile.displayName": "Full Name",
    "profile.loginCode": "Login Code",
    "profile.personnelCode": "Personnel Code",
    "profile.language": "Language Preference",
    "profile.save": "Save",
    "profile.saved": "Saved",
    "profile.show": "Show",
    "profile.hide": "Hide",
    "profile.copy": "Copy",
    "profile.copied": "Copied",
    "nav.profile": "Profile",
  },
  de: {
    "landing.title": "ERPVerse",
    "landing.subtitle": "Einheitliche Unternehmensmanagementplattform",
    "landing.description": "Verwalten Sie Ihr Unternehmen von einer Plattform",
    "portal.owner": "Unternehmensinhaber",
    "portal.owner.desc": "Unternehmen einrichten oder verwalten",
    "portal.manager": "Unternehmensleiter",
    "portal.manager.desc": "Zugang zum Managerpanel",
    "portal.admin": "Unternehmensadmin",
    "portal.admin.desc": "Zugang zum Adminpanel",
    "portal.employee": "Unternehmensmitarbeiter",
    "portal.employee.desc": "Zugang zum Mitarbeiterpanel",
    "auth.login": "Anmelden",
    "auth.register": "Registrieren",
    "auth.loginCode": "Ihr Anmeldecode",
    "auth.personnelCode": "Ihr Personalcode",
    "auth.fullName": "Vollständiger Name",
    "auth.enterCode": "Code eingeben",
    "auth.enterName": "Name eingeben",
    "auth.submit": "Weiter",
    "auth.backToLogin": "Anmelden",
    "auth.noCompany": "Sie gehören noch keinem Unternehmen an.",
    "code.title": "Registrierung erfolgreich!",
    "code.subtitle": "Speichern Sie die folgenden Codes an einem sicheren Ort.",
    "code.loginCode": "Ihr Anmeldecode",
    "code.personnelCode": "Ihr Personalcode",
    "code.copied": "Kopiert!",
    "code.copy": "Kopieren",
    "code.continue": "Anmelden",
    "company.setup.title": "Unternehmenseinrichtung",
    "company.setup.subtitle": "Geben Sie Ihre Unternehmensdaten ein",
    "company.name": "Unternehmensname",
    "company.sector": "Branche",
    "company.address": "Adresse",
    "company.email": "Kontakt-E-Mail",
    "company.phone": "Telefon",
    "company.foundedYear": "Gründungsjahr",
    "company.create": "Unternehmen erstellen",
    "company.select.title": "Unternehmen auswählen",
    "company.select.subtitle": "Auf welches Unternehmen möchten Sie zugreifen?",
    "dashboard.overview": "Überblick",
    "dashboard.personnel": "Personalverwaltung",
    "dashboard.modules": "Modulberechtigungen",
    "dashboard.settings": "Einstellungen",
    "dashboard.employees": "Mitarbeiter gesamt",
    "dashboard.activeModules": "Aktive Module",
    "dashboard.company": "Unternehmen",
    "personnel.add": "Personal hinzufügen",
    "personnel.code": "Personalcode",
    "personnel.role": "Rolle",
    "personnel.modules": "Module",
    "personnel.remove": "Entfernen",
    "personnel.added": "Personal erfolgreich hinzugefügt",
    "personnel.removed": "Personal entfernt",
    "personnel.notFound": "Personal nicht gefunden",
    "personnel.noMembers": "Noch kein Personal hinzugefügt",
    "role.owner": "Unternehmensinhaber",
    "role.manager": "Unternehmensleiter",
    "role.admin": "Unternehmensadmin",
    "role.employee": "Mitarbeiter",
    "modules.HR": "Personalwesen",
    "modules.Accounting": "Buchhaltung",
    "modules.CRM": "CRM",
    "modules.Inventory": "Inventar",
    "modules.Projects": "Projekte",
    "modules.Purchasing": "Einkauf",
    "modules.Production": "Produktion",
    "modules.Workflow": "Arbeitsablauf",
    "modules.Reporting": "Berichte",
    "nav.logout": "Abmelden",
    "nav.back": "Zurück",
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.loading": "Laden...",
    "common.error": "Fehler aufgetreten",
    "common.success": "Erfolgreich",
    "module.comingSoon": "Dieses Modul wird bald aktiv",
    "purchasing.title": "Einkauf",
    "purchasing.supplier": "Lieferant",
    "purchasing.amount": "Betrag",
    "purchasing.date": "Datum",
    "purchasing.status": "Status",
    "purchasing.addOrder": "Bestellung hinzufügen",
    "purchasing.pending": "Ausstehend",
    "purchasing.approved": "Genehmigt",
    "purchasing.delivered": "Geliefert",
    "purchasing.totalOrders": "Gesamtbestellungen",
    "production.title": "Produktion",
    "production.product": "Produkt",
    "production.quantity": "Menge",
    "production.progress": "Fortschritt",
    "production.status": "Status",
    "production.addOrder": "Produktion hinzufügen",
    "production.planned": "Geplant",
    "production.inProgress": "In Bearbeitung",
    "production.completed": "Abgeschlossen",
    "workflow.title": "Workflow",
    "workflow.task": "Aufgabe",
    "workflow.assignee": "Zugewiesen an",
    "workflow.priority": "Priorität",
    "workflow.status": "Status",
    "workflow.addTask": "Aufgabe hinzufügen",
    "workflow.high": "Hoch",
    "workflow.medium": "Mittel",
    "workflow.low": "Niedrig",
    "workflow.pending": "Ausstehend",
    "workflow.inProgress": "In Bearbeitung",
    "workflow.done": "Erledigt",
    "reporting.title": "Berichte",
    "reporting.revenue": "Umsatz",
    "reporting.expenses": "Ausgaben",
    "reporting.netProfit": "Nettogewinn",
    "reporting.employees": "Mitarbeiter",
    "reporting.monthlyChart": "Monatliches Diagramm",
    "reporting.moduleUsage": "Modulnutzung",
    "reporting.totalEmployees": "Mitarbeiter gesamt",
    "reporting.active": "aktiv",
    "reporting.totalTransactions": "Transaktionen gesamt",
    "reporting.totalCustomers": "Kunden gesamt",
    "reporting.totalProducts": "Produkte gesamt",
    "reporting.totalProjects": "Projekte gesamt",
    "reporting.openOrders": "Offene Bestellungen",
    "reporting.productionOrders": "Produktionsaufträge",
    "reporting.workflowTasks": "Workflow-Aufgaben",
    "reporting.totalRecords": "Einträge gesamt",
    "reporting.noData": "Noch keine Daten",
    "reporting.noDataSub": "Fügen Sie Daten zu Modulen hinzu",
    "reporting.dataSummary": "Modul-Datenzusammenfassung",
    "hr.title": "Personalwesen",
    "hr.employee": "Mitarbeiter",
    "hr.position": "Position",
    "hr.department": "Abteilung",
    "hr.status": "Status",
    "hr.active": "Aktiv",
    "hr.onLeave": "Im Urlaub",
    "hr.terminated": "Ausgeschieden",
    "hr.addEmployee": "Mitarbeiter hinzufügen",
    "hr.totalEmployees": "Gesamtmitarbeiter",
    "hr.searchEmployee": "Mitarbeiter suchen...",
    "accounting.title": "Buchhaltung",
    "accounting.income": "Einnahmen",
    "accounting.expense": "Ausgaben",
    "accounting.balance": "Nettosaldo",
    "accounting.description": "Beschreibung",
    "accounting.amount": "Betrag",
    "accounting.date": "Datum",
    "accounting.category": "Kategorie",
    "accounting.addTransaction": "Transaktion hinzufügen",
    "accounting.type": "Typ",
    "crm.title": "Kundenbeziehungen",
    "crm.customer": "Kunde",
    "crm.lead": "Lead",
    "crm.email": "E-Mail",
    "crm.phone": "Telefon",
    "crm.status": "Status",
    "crm.addCustomer": "Kunde hinzufügen",
    "crm.lead_status": "Lead",
    "crm.active_status": "Aktiv",
    "crm.closed_status": "Geschlossen",
    "inventory.title": "Inventar",
    "inventory.product": "Produkt",
    "inventory.category": "Kategorie",
    "inventory.quantity": "Menge",
    "inventory.unitPrice": "Stückpreis",
    "inventory.totalValue": "Gesamtwert",
    "inventory.addProduct": "Produkt hinzufügen",
    "inventory.lowStock": "Niedriger Bestand",
    "projects.title": "Projekte",
    "projects.project": "Projekt",
    "projects.status": "Status",
    "projects.startDate": "Startdatum",
    "projects.endDate": "Enddatum",
    "projects.team": "Personen",
    "projects.addProject": "Projekt hinzufügen",
    "projects.planning_status": "Planung",
    "projects.active_status": "Aktiv",
    "projects.completed_status": "Abgeschlossen",
    "projects.paused_status": "Pausiert",
    "projects.tasks": "Aufgaben",
    "settings.title": "Unternehmenseinstellungen",
    "supplier.title": "Lieferanten",
    "supplier.add": "Lieferant hinzufügen",
    "supplier.edit": "Lieferant bearbeiten",
    "supplier.name": "Lieferantenname",
    "supplier.contact": "Kontaktperson",
    "supplier.phone": "Telefon",
    "supplier.email": "E-Mail",
    "supplier.category": "Kategorie",
    "supplier.paymentTerms": "Zahlungsbedingungen",
    "supplier.rating": "Bewertung",
    "supplier.notes": "Notizen",
    "supplier.totalSuppliers": "Lieferanten gesamt",
    "purchasing.tabs.orders": "Bestellungen",
    "purchasing.tabs.suppliers": "Lieferanten",
    "profile.title": "Profileinstellungen",
    "profile.displayName": "Vollständiger Name",
    "profile.loginCode": "Anmeldecode",
    "profile.personnelCode": "Personalcode",
    "profile.language": "Sprachpräferenz",
    "profile.save": "Speichern",
    "profile.saved": "Gespeichert",
    "profile.show": "Anzeigen",
    "profile.hide": "Ausblenden",
    "profile.copy": "Kopieren",
    "profile.copied": "Kopiert",
    "nav.profile": "Profil",
  },
  fr: {
    "landing.title": "ERPVerse",
    "landing.subtitle": "Plateforme de gestion unifiée",
    "landing.description": "Gérez votre entreprise depuis une seule plateforme",
    "portal.owner": "Propriétaire",
    "portal.owner.desc": "Configurer ou gérer l'entreprise",
    "portal.manager": "Directeur",
    "portal.manager.desc": "Accéder au panel directeur",
    "portal.admin": "Administrateur",
    "portal.admin.desc": "Accéder au panel admin",
    "portal.employee": "Employé",
    "portal.employee.desc": "Accéder au panel employé",
    "auth.login": "Se connecter",
    "auth.register": "S'inscrire",
    "auth.loginCode": "Votre code de connexion",
    "auth.personnelCode": "Votre code personnel",
    "auth.fullName": "Nom complet",
    "auth.enterCode": "Entrez votre code",
    "auth.enterName": "Entrez votre nom",
    "auth.submit": "Continuer",
    "auth.backToLogin": "Se connecter",
    "auth.noCompany": "Vous ne faites pas encore partie d'une entreprise.",
    "code.title": "Inscription réussie!",
    "code.subtitle": "Sauvegardez ces codes dans un endroit sûr.",
    "code.loginCode": "Votre code de connexion",
    "code.personnelCode": "Votre code personnel",
    "code.copied": "Copié!",
    "code.copy": "Copier",
    "code.continue": "Se connecter",
    "company.setup.title": "Configuration de l'entreprise",
    "company.setup.subtitle": "Entrez les détails de votre entreprise",
    "company.name": "Nom de l'entreprise",
    "company.sector": "Secteur",
    "company.address": "Adresse",
    "company.email": "Email de contact",
    "company.phone": "Téléphone",
    "company.foundedYear": "Année de fondation",
    "company.create": "Créer l'entreprise",
    "company.select.title": "Sélectionner une entreprise",
    "company.select.subtitle": "À quelle entreprise souhaitez-vous accéder?",
    "dashboard.overview": "Aperçu",
    "dashboard.personnel": "Gestion du personnel",
    "dashboard.modules": "Autorisations modules",
    "dashboard.settings": "Paramètres",
    "dashboard.employees": "Total employés",
    "dashboard.activeModules": "Modules actifs",
    "dashboard.company": "Entreprise",
    "personnel.add": "Ajouter personnel",
    "personnel.code": "Code personnel",
    "personnel.role": "Rôle",
    "personnel.modules": "Modules",
    "personnel.remove": "Retirer",
    "personnel.added": "Personnel ajouté avec succès",
    "personnel.removed": "Personnel retiré",
    "personnel.notFound": "Personnel non trouvé",
    "personnel.noMembers": "Aucun personnel ajouté",
    "role.owner": "Propriétaire",
    "role.manager": "Directeur",
    "role.admin": "Administrateur",
    "role.employee": "Employé",
    "modules.HR": "RH",
    "modules.Accounting": "Comptabilité",
    "modules.CRM": "CRM",
    "modules.Inventory": "Inventaire",
    "modules.Projects": "Projets",
    "modules.Purchasing": "Achats",
    "modules.Production": "Production",
    "modules.Workflow": "Flux de travail",
    "modules.Reporting": "Rapports",
    "nav.logout": "Déconnexion",
    "nav.back": "Retour",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.loading": "Chargement...",
    "common.error": "Erreur survenue",
    "common.success": "Succès",
    "module.comingSoon": "Ce module sera bientôt actif",
    "purchasing.title": "Achats",
    "purchasing.supplier": "Fournisseur",
    "purchasing.amount": "Montant",
    "purchasing.date": "Date",
    "purchasing.status": "Statut",
    "purchasing.addOrder": "Ajouter commande",
    "purchasing.pending": "En attente",
    "purchasing.approved": "Approuvé",
    "purchasing.delivered": "Livré",
    "purchasing.totalOrders": "Total commandes",
    "production.title": "Production",
    "production.product": "Produit",
    "production.quantity": "Quantité",
    "production.progress": "Progression",
    "production.status": "Statut",
    "production.addOrder": "Ajouter production",
    "production.planned": "Planifié",
    "production.inProgress": "En cours",
    "production.completed": "Terminé",
    "workflow.title": "Flux de travail",
    "workflow.task": "Tâche",
    "workflow.assignee": "Assigné à",
    "workflow.priority": "Priorité",
    "workflow.status": "Statut",
    "workflow.addTask": "Ajouter tâche",
    "workflow.high": "Haute",
    "workflow.medium": "Moyenne",
    "workflow.low": "Basse",
    "workflow.pending": "En attente",
    "workflow.inProgress": "En cours",
    "workflow.done": "Terminé",
    "reporting.title": "Rapports",
    "reporting.revenue": "Revenus",
    "reporting.expenses": "Dépenses",
    "reporting.netProfit": "Bénéfice net",
    "reporting.employees": "Employés",
    "reporting.monthlyChart": "Graphique mensuel",
    "reporting.moduleUsage": "Utilisation des modules",
    "reporting.totalEmployees": "Employés totaux",
    "reporting.active": "actif",
    "reporting.totalTransactions": "Transactions totales",
    "reporting.totalCustomers": "Clients totaux",
    "reporting.totalProducts": "Produits totaux",
    "reporting.totalProjects": "Projets totaux",
    "reporting.openOrders": "Commandes ouvertes",
    "reporting.productionOrders": "Ordres de production",
    "reporting.workflowTasks": "Tâches de flux",
    "reporting.totalRecords": "Total des enregistrements",
    "reporting.noData": "Pas encore de données",
    "reporting.noDataSub": "Ajoutez des données aux modules",
    "reporting.dataSummary": "Résumé des données de module",
    "hr.title": "Ressources Humaines",
    "hr.employee": "Employé",
    "hr.position": "Poste",
    "hr.department": "Département",
    "hr.status": "Statut",
    "hr.active": "Actif",
    "hr.onLeave": "En congé",
    "hr.terminated": "Terminé",
    "hr.addEmployee": "Ajouter employé",
    "hr.totalEmployees": "Total employés",
    "hr.searchEmployee": "Rechercher employé...",
    "accounting.title": "Comptabilité",
    "accounting.income": "Revenus",
    "accounting.expense": "Dépenses",
    "accounting.balance": "Solde net",
    "accounting.description": "Description",
    "accounting.amount": "Montant",
    "accounting.date": "Date",
    "accounting.category": "Catégorie",
    "accounting.addTransaction": "Ajouter transaction",
    "accounting.type": "Type",
    "crm.title": "Relations clients",
    "crm.customer": "Client",
    "crm.lead": "Prospect",
    "crm.email": "Email",
    "crm.phone": "Téléphone",
    "crm.status": "Statut",
    "crm.addCustomer": "Ajouter client",
    "crm.lead_status": "Prospect",
    "crm.active_status": "Actif",
    "crm.closed_status": "Fermé",
    "inventory.title": "Inventaire",
    "inventory.product": "Produit",
    "inventory.category": "Catégorie",
    "inventory.quantity": "Quantité",
    "inventory.unitPrice": "Prix unitaire",
    "inventory.totalValue": "Valeur totale",
    "inventory.addProduct": "Ajouter produit",
    "inventory.lowStock": "Stock faible",
    "projects.title": "Projets",
    "projects.project": "Projet",
    "projects.status": "Statut",
    "projects.startDate": "Date début",
    "projects.endDate": "Date fin",
    "projects.team": "Membres",
    "projects.addProject": "Ajouter projet",
    "projects.planning_status": "Planification",
    "projects.active_status": "Actif",
    "projects.completed_status": "Terminé",
    "projects.paused_status": "En pause",
    "projects.tasks": "Tâches",
    "settings.title": "Paramètres entreprise",
  },
  es: {
    "landing.title": "ERPVerse",
    "landing.subtitle": "Plataforma unificada de gestión empresarial",
    "landing.description": "Gestiona tu empresa desde una sola plataforma",
    "portal.owner": "Propietario",
    "portal.owner.desc": "Configurar o gestionar empresa",
    "portal.manager": "Gerente",
    "portal.manager.desc": "Acceder al panel gerente",
    "portal.admin": "Administrador",
    "portal.admin.desc": "Acceder al panel admin",
    "portal.employee": "Empleado",
    "portal.employee.desc": "Acceder al panel empleado",
    "auth.login": "Iniciar sesión",
    "auth.register": "Registrarse",
    "auth.loginCode": "Tu código de acceso",
    "auth.personnelCode": "Tu código de personal",
    "auth.fullName": "Nombre completo",
    "auth.enterCode": "Ingresa tu código",
    "auth.enterName": "Ingresa tu nombre",
    "auth.submit": "Continuar",
    "auth.backToLogin": "Iniciar sesión",
    "auth.noCompany": "Aún no perteneces a ninguna empresa.",
    "code.title": "¡Registro exitoso!",
    "code.subtitle": "Guarda estos códigos en un lugar seguro.",
    "code.loginCode": "Tu código de acceso",
    "code.personnelCode": "Tu código de personal",
    "code.copied": "¡Copiado!",
    "code.copy": "Copiar",
    "code.continue": "Iniciar sesión",
    "company.setup.title": "Configuración de empresa",
    "company.setup.subtitle": "Ingresa los datos de tu empresa",
    "company.name": "Nombre de empresa",
    "company.sector": "Sector",
    "company.address": "Dirección",
    "company.email": "Email de contacto",
    "company.phone": "Teléfono",
    "company.foundedYear": "Año de fundación",
    "company.create": "Crear empresa",
    "company.select.title": "Seleccionar empresa",
    "company.select.subtitle": "¿A qué empresa deseas acceder?",
    "dashboard.overview": "Resumen",
    "dashboard.personnel": "Gestión de personal",
    "dashboard.modules": "Permisos de módulos",
    "dashboard.settings": "Configuración",
    "dashboard.employees": "Total empleados",
    "dashboard.activeModules": "Módulos activos",
    "dashboard.company": "Empresa",
    "personnel.add": "Agregar personal",
    "personnel.code": "Código personal",
    "personnel.role": "Rol",
    "personnel.modules": "Módulos",
    "personnel.remove": "Quitar",
    "personnel.added": "Personal agregado exitosamente",
    "personnel.removed": "Personal quitado",
    "personnel.notFound": "Personal no encontrado",
    "personnel.noMembers": "Sin personal aún",
    "role.owner": "Propietario",
    "role.manager": "Gerente",
    "role.admin": "Administrador",
    "role.employee": "Empleado",
    "modules.HR": "RRHH",
    "modules.Accounting": "Contabilidad",
    "modules.CRM": "CRM",
    "modules.Inventory": "Inventario",
    "modules.Projects": "Proyectos",
    "modules.Purchasing": "Compras",
    "modules.Production": "Producción",
    "modules.Workflow": "Flujo de trabajo",
    "modules.Reporting": "Reportes",
    "nav.logout": "Cerrar sesión",
    "nav.back": "Atrás",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.loading": "Cargando...",
    "common.error": "Error ocurrido",
    "common.success": "Éxito",
    "module.comingSoon": "Este módulo estará activo pronto",
    "purchasing.title": "Compras",
    "purchasing.supplier": "Proveedor",
    "purchasing.amount": "Importe",
    "purchasing.date": "Fecha",
    "purchasing.status": "Estado",
    "purchasing.addOrder": "Añadir pedido",
    "purchasing.pending": "Pendiente",
    "purchasing.approved": "Aprobado",
    "purchasing.delivered": "Entregado",
    "purchasing.totalOrders": "Total pedidos",
    "production.title": "Producción",
    "production.product": "Producto",
    "production.quantity": "Cantidad",
    "production.progress": "Progreso",
    "production.status": "Estado",
    "production.addOrder": "Añadir producción",
    "production.planned": "Planificado",
    "production.inProgress": "En progreso",
    "production.completed": "Completado",
    "workflow.title": "Flujo de trabajo",
    "workflow.task": "Tarea",
    "workflow.assignee": "Asignado a",
    "workflow.priority": "Prioridad",
    "workflow.status": "Estado",
    "workflow.addTask": "Añadir tarea",
    "workflow.high": "Alta",
    "workflow.medium": "Media",
    "workflow.low": "Baja",
    "workflow.pending": "Pendiente",
    "workflow.inProgress": "En progreso",
    "workflow.done": "Hecho",
    "reporting.title": "Informes",
    "reporting.revenue": "Ingresos",
    "reporting.expenses": "Gastos",
    "reporting.netProfit": "Beneficio neto",
    "reporting.employees": "Empleados",
    "reporting.monthlyChart": "Gráfico mensual",
    "reporting.moduleUsage": "Uso de módulos",
    "reporting.totalEmployees": "Empleados totales",
    "reporting.active": "activo",
    "reporting.totalTransactions": "Transacciones totales",
    "reporting.totalCustomers": "Clientes totales",
    "reporting.totalProducts": "Productos totales",
    "reporting.totalProjects": "Proyectos totales",
    "reporting.openOrders": "Pedidos abiertos",
    "reporting.productionOrders": "Órdenes de producción",
    "reporting.workflowTasks": "Tareas de flujo",
    "reporting.totalRecords": "Total de registros",
    "reporting.noData": "Sin datos aún",
    "reporting.noDataSub": "Agrega datos a los módulos",
    "reporting.dataSummary": "Resumen de datos del módulo",
    "hr.title": "Recursos Humanos",
    "hr.employee": "Empleado",
    "hr.position": "Puesto",
    "hr.department": "Departamento",
    "hr.status": "Estado",
    "hr.active": "Activo",
    "hr.onLeave": "De baja",
    "hr.terminated": "Terminado",
    "hr.addEmployee": "Agregar empleado",
    "hr.totalEmployees": "Total empleados",
    "hr.searchEmployee": "Buscar empleado...",
    "accounting.title": "Contabilidad",
    "accounting.income": "Ingresos",
    "accounting.expense": "Gastos",
    "accounting.balance": "Balance neto",
    "accounting.description": "Descripción",
    "accounting.amount": "Monto",
    "accounting.date": "Fecha",
    "accounting.category": "Categoría",
    "accounting.addTransaction": "Agregar transacción",
    "accounting.type": "Tipo",
    "crm.title": "Relaciones con clientes",
    "crm.customer": "Cliente",
    "crm.lead": "Prospecto",
    "crm.email": "Email",
    "crm.phone": "Teléfono",
    "crm.status": "Estado",
    "crm.addCustomer": "Agregar cliente",
    "crm.lead_status": "Prospecto",
    "crm.active_status": "Activo",
    "crm.closed_status": "Cerrado",
    "inventory.title": "Inventario",
    "inventory.product": "Producto",
    "inventory.category": "Categoría",
    "inventory.quantity": "Cantidad",
    "inventory.unitPrice": "Precio unitario",
    "inventory.totalValue": "Valor total",
    "inventory.addProduct": "Agregar producto",
    "inventory.lowStock": "Stock bajo",
    "projects.title": "Proyectos",
    "projects.project": "Proyecto",
    "projects.status": "Estado",
    "projects.startDate": "Fecha inicio",
    "projects.endDate": "Fecha fin",
    "projects.team": "Miembros",
    "projects.addProject": "Agregar proyecto",
    "projects.planning_status": "Planificación",
    "projects.active_status": "Activo",
    "projects.completed_status": "Completado",
    "projects.paused_status": "Pausado",
    "projects.tasks": "Tareas",
    "settings.title": "Configuración empresa",
  },
  ar: {
    "landing.title": "ERPVerse",
    "landing.subtitle": "منصة إدارة الأعمال الموحدة",
    "landing.description": "إدارة شركتك من منصة واحدة",
    "portal.owner": "صاحب الشركة",
    "portal.owner.desc": "إعداد أو إدارة الشركة",
    "portal.manager": "مدير الشركة",
    "portal.manager.desc": "الدخول إلى لوحة المدير",
    "portal.admin": "مشرف الشركة",
    "portal.admin.desc": "الدخول إلى لوحة المشرف",
    "portal.employee": "موظف الشركة",
    "portal.employee.desc": "الدخول إلى لوحة الموظف",
    "auth.login": "تسجيل الدخول",
    "auth.register": "التسجيل",
    "auth.loginCode": "رمز الدخول",
    "auth.personnelCode": "رمز الموظف",
    "auth.fullName": "الاسم الكامل",
    "auth.enterCode": "أدخل الرمز",
    "auth.enterName": "أدخل اسمك",
    "auth.submit": "متابعة",
    "auth.backToLogin": "تسجيل الدخول",
    "auth.noCompany": "لست عضواً في أي شركة بعد.",
    "code.title": "تم التسجيل بنجاح!",
    "code.subtitle": "احفظ هذه الرموز في مكان آمن.",
    "code.loginCode": "رمز الدخول",
    "code.personnelCode": "رمز الموظف",
    "code.copied": "تم النسخ!",
    "code.copy": "نسخ",
    "code.continue": "تسجيل الدخول",
    "company.setup.title": "إعداد الشركة",
    "company.setup.subtitle": "أدخل بيانات شركتك",
    "company.name": "اسم الشركة",
    "company.sector": "القطاع",
    "company.address": "العنوان",
    "company.email": "البريد الإلكتروني",
    "company.phone": "الهاتف",
    "company.foundedYear": "سنة التأسيس",
    "company.create": "إنشاء الشركة",
    "company.select.title": "اختر الشركة",
    "company.select.subtitle": "أي شركة تريد الدخول إليها؟",
    "dashboard.overview": "نظرة عامة",
    "dashboard.personnel": "إدارة الموظفين",
    "dashboard.modules": "صلاحيات الوحدات",
    "dashboard.settings": "الإعدادات",
    "dashboard.employees": "إجمالي الموظفين",
    "dashboard.activeModules": "الوحدات النشطة",
    "dashboard.company": "الشركة",
    "personnel.add": "إضافة موظف",
    "personnel.code": "رمز الموظف",
    "personnel.role": "الدور",
    "personnel.modules": "الوحدات",
    "personnel.remove": "إزالة",
    "personnel.added": "تمت إضافة الموظف بنجاح",
    "personnel.removed": "تمت إزالة الموظف",
    "personnel.notFound": "الموظف غير موجود",
    "personnel.noMembers": "لا يوجد موظفون بعد",
    "role.owner": "صاحب الشركة",
    "role.manager": "مدير الشركة",
    "role.admin": "مشرف الشركة",
    "role.employee": "موظف",
    "modules.HR": "الموارد البشرية",
    "modules.Accounting": "المحاسبة",
    "modules.CRM": "إدارة العملاء",
    "modules.Inventory": "المخزون",
    "modules.Projects": "المشاريع",
    "modules.Purchasing": "المشتريات",
    "modules.Production": "الإنتاج",
    "modules.Workflow": "سير العمل",
    "modules.Reporting": "التقارير",
    "nav.logout": "تسجيل الخروج",
    "nav.back": "رجوع",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.loading": "جار التحميل...",
    "common.error": "حدث خطأ",
    "common.success": "نجح",
    "module.comingSoon": "هذه الوحدة ستكون نشطة قريباً",
    "purchasing.title": "المشتريات",
    "purchasing.supplier": "المورد",
    "purchasing.amount": "المبلغ",
    "purchasing.date": "التاريخ",
    "purchasing.status": "الحالة",
    "purchasing.addOrder": "إضافة طلب",
    "purchasing.pending": "معلق",
    "purchasing.approved": "موافق عليه",
    "purchasing.delivered": "تم التسليم",
    "purchasing.totalOrders": "إجمالي الطلبات",
    "production.title": "الإنتاج",
    "production.product": "المنتج",
    "production.quantity": "الكمية",
    "production.progress": "التقدم",
    "production.status": "الحالة",
    "production.addOrder": "إضافة إنتاج",
    "production.planned": "مخطط",
    "production.inProgress": "قيد التنفيذ",
    "production.completed": "مكتمل",
    "workflow.title": "سير العمل",
    "workflow.task": "مهمة",
    "workflow.assignee": "المسؤول",
    "workflow.priority": "الأولوية",
    "workflow.status": "الحالة",
    "workflow.addTask": "إضافة مهمة",
    "workflow.high": "عالية",
    "workflow.medium": "متوسطة",
    "workflow.low": "منخفضة",
    "workflow.pending": "معلق",
    "workflow.inProgress": "قيد التنفيذ",
    "workflow.done": "منجز",
    "reporting.title": "التقارير",
    "reporting.revenue": "الإيرادات",
    "reporting.expenses": "المصروفات",
    "reporting.netProfit": "صافي الربح",
    "reporting.employees": "الموظفون",
    "reporting.monthlyChart": "الرسم الشهري",
    "reporting.moduleUsage": "استخدام الوحدات",
    "reporting.totalEmployees": "إجمالي الموظفين",
    "reporting.active": "نشط",
    "reporting.totalTransactions": "إجمالي المعاملات",
    "reporting.totalCustomers": "إجمالي العملاء",
    "reporting.totalProducts": "إجمالي المنتجات",
    "reporting.totalProjects": "إجمالي المشاريع",
    "reporting.openOrders": "الطلبات المفتوحة",
    "reporting.productionOrders": "أوامر الإنتاج",
    "reporting.workflowTasks": "مهام سير العمل",
    "reporting.totalRecords": "إجمالي السجلات",
    "reporting.noData": "لا توجد بيانات بعد",
    "reporting.noDataSub": "أضف بيانات إلى الوحدات",
    "reporting.dataSummary": "ملخص بيانات الوحدات",
    "hr.title": "الموارد البشرية",
    "hr.employee": "موظف",
    "hr.position": "المنصب",
    "hr.department": "القسم",
    "hr.status": "الحالة",
    "hr.active": "نشط",
    "hr.onLeave": "في إجازة",
    "hr.terminated": "منتهي",
    "hr.addEmployee": "إضافة موظف",
    "hr.totalEmployees": "إجمالي الموظفين",
    "hr.searchEmployee": "ابحث عن موظف...",
    "accounting.title": "المحاسبة",
    "accounting.income": "الدخل",
    "accounting.expense": "المصروفات",
    "accounting.balance": "الرصيد الصافي",
    "accounting.description": "الوصف",
    "accounting.amount": "المبلغ",
    "accounting.date": "التاريخ",
    "accounting.category": "الفئة",
    "accounting.addTransaction": "إضافة معاملة",
    "accounting.type": "النوع",
    "crm.title": "علاقات العملاء",
    "crm.customer": "عميل",
    "crm.lead": "عميل محتمل",
    "crm.email": "البريد الإلكتروني",
    "crm.phone": "الهاتف",
    "crm.status": "الحالة",
    "crm.addCustomer": "إضافة عميل",
    "crm.lead_status": "محتمل",
    "crm.active_status": "نشط",
    "crm.closed_status": "مغلق",
    "inventory.title": "إدارة المخزون",
    "inventory.product": "منتج",
    "inventory.category": "الفئة",
    "inventory.quantity": "الكمية",
    "inventory.unitPrice": "سعر الوحدة",
    "inventory.totalValue": "القيمة الإجمالية",
    "inventory.addProduct": "إضافة منتج",
    "inventory.lowStock": "مخزون منخفض",
    "projects.title": "المشاريع",
    "projects.project": "مشروع",
    "projects.status": "الحالة",
    "projects.startDate": "تاريخ البدء",
    "projects.endDate": "تاريخ الانتهاء",
    "projects.team": "أعضاء",
    "projects.addProject": "إضافة مشروع",
    "projects.planning_status": "تخطيط",
    "projects.active_status": "نشط",
    "projects.completed_status": "مكتمل",
    "projects.paused_status": "متوقف",
    "projects.tasks": "المهام",
    "settings.title": "إعدادات الشركة",
    "supplier.title": "الموردون",
    "supplier.add": "إضافة مورد",
    "supplier.edit": "تعديل المورد",
    "supplier.name": "اسم المورد",
    "supplier.contact": "شخص الاتصال",
    "supplier.phone": "الهاتف",
    "supplier.email": "البريد الإلكتروني",
    "supplier.category": "الفئة",
    "supplier.paymentTerms": "شروط الدفع",
    "supplier.rating": "التقييم",
    "supplier.notes": "ملاحظات",
    "supplier.totalSuppliers": "إجمالي الموردين",
    "purchasing.tabs.orders": "الطلبات",
    "purchasing.tabs.suppliers": "الموردون",
    "profile.title": "إعدادات الملف الشخصي",
    "profile.displayName": "الاسم الكامل",
    "profile.loginCode": "رمز الدخول",
    "profile.personnelCode": "رمز الموظف",
    "profile.language": "تفضيل اللغة",
    "profile.save": "حفظ",
    "profile.saved": "تم الحفظ",
    "profile.show": "إظهار",
    "profile.hide": "إخفاء",
    "profile.copy": "نسخ",
    "profile.copied": "تم النسخ",
    "nav.profile": "الملف الشخصي",
  },
  ru: {
    "landing.title": "ERPVerse",
    "landing.subtitle": "Единая платформа управления бизнесом",
    "landing.description": "Управляйте компанией с одной платформы",
    "portal.owner": "Владелец компании",
    "portal.owner.desc": "Настройка или управление компанией",
    "portal.manager": "Менеджер компании",
    "portal.manager.desc": "Войти в панель менеджера",
    "portal.admin": "Администратор",
    "portal.admin.desc": "Войти в панель администратора",
    "portal.employee": "Сотрудник",
    "portal.employee.desc": "Войти в панель сотрудника",
    "auth.login": "Войти",
    "auth.register": "Зарегистрироваться",
    "auth.loginCode": "Ваш код входа",
    "auth.personnelCode": "Ваш код сотрудника",
    "auth.fullName": "Полное имя",
    "auth.enterCode": "Введите код",
    "auth.enterName": "Введите имя",
    "auth.submit": "Продолжить",
    "auth.backToLogin": "Войти",
    "auth.noCompany": "Вы ещё не состоите в компании.",
    "code.title": "Регистрация успешна!",
    "code.subtitle": "Сохраните коды в надёжном месте.",
    "code.loginCode": "Ваш код входа",
    "code.personnelCode": "Ваш код сотрудника",
    "code.copied": "Скопировано!",
    "code.copy": "Копировать",
    "code.continue": "Войти",
    "company.setup.title": "Настройка компании",
    "company.setup.subtitle": "Введите данные компании",
    "company.name": "Название компании",
    "company.sector": "Отрасль",
    "company.address": "Адрес",
    "company.email": "Контактный email",
    "company.phone": "Телефон",
    "company.foundedYear": "Год основания",
    "company.create": "Создать компанию",
    "company.select.title": "Выбор компании",
    "company.select.subtitle": "В какую компанию хотите войти?",
    "dashboard.overview": "Обзор",
    "dashboard.personnel": "Управление персоналом",
    "dashboard.modules": "Разрешения модулей",
    "dashboard.settings": "Настройки",
    "dashboard.employees": "Всего сотрудников",
    "dashboard.activeModules": "Активные модули",
    "dashboard.company": "Компания",
    "personnel.add": "Добавить персонал",
    "personnel.code": "Код персонала",
    "personnel.role": "Роль",
    "personnel.modules": "Модули",
    "personnel.remove": "Удалить",
    "personnel.added": "Персонал успешно добавлен",
    "personnel.removed": "Персонал удалён",
    "personnel.notFound": "Персонал не найден",
    "personnel.noMembers": "Персонал ещё не добавлен",
    "role.owner": "Владелец",
    "role.manager": "Менеджер",
    "role.admin": "Администратор",
    "role.employee": "Сотрудник",
    "modules.HR": "HR",
    "modules.Accounting": "Бухгалтерия",
    "modules.CRM": "CRM",
    "modules.Inventory": "Склад",
    "modules.Projects": "Проекты",
    "modules.Purchasing": "Закупки",
    "modules.Production": "Производство",
    "modules.Workflow": "Рабочий процесс",
    "modules.Reporting": "Отчёты",
    "nav.logout": "Выйти",
    "nav.back": "Назад",
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.loading": "Загрузка...",
    "common.error": "Произошла ошибка",
    "common.success": "Успешно",
    "module.comingSoon": "Этот модуль скоро будет активен",
    "purchasing.title": "Закупки",
    "purchasing.supplier": "Поставщик",
    "purchasing.amount": "Сумма",
    "purchasing.date": "Дата",
    "purchasing.status": "Статус",
    "purchasing.addOrder": "Добавить заказ",
    "purchasing.pending": "Ожидает",
    "purchasing.approved": "Одобрено",
    "purchasing.delivered": "Доставлено",
    "purchasing.totalOrders": "Всего заказов",
    "production.title": "Производство",
    "production.product": "Продукт",
    "production.quantity": "Количество",
    "production.progress": "Прогресс",
    "production.status": "Статус",
    "production.addOrder": "Добавить производство",
    "production.planned": "Запланировано",
    "production.inProgress": "В процессе",
    "production.completed": "Завершено",
    "workflow.title": "Рабочий процесс",
    "workflow.task": "Задача",
    "workflow.assignee": "Исполнитель",
    "workflow.priority": "Приоритет",
    "workflow.status": "Статус",
    "workflow.addTask": "Добавить задачу",
    "workflow.high": "Высокий",
    "workflow.medium": "Средний",
    "workflow.low": "Низкий",
    "workflow.pending": "Ожидает",
    "workflow.inProgress": "В процессе",
    "workflow.done": "Выполнено",
    "reporting.title": "Отчёты",
    "reporting.revenue": "Доходы",
    "reporting.expenses": "Расходы",
    "reporting.netProfit": "Чистая прибыль",
    "reporting.employees": "Сотрудники",
    "reporting.monthlyChart": "Месячный график",
    "reporting.moduleUsage": "Использование модулей",
    "reporting.totalEmployees": "Всего сотрудников",
    "reporting.active": "активных",
    "reporting.totalTransactions": "Всего транзакций",
    "reporting.totalCustomers": "Всего клиентов",
    "reporting.totalProducts": "Всего продуктов",
    "reporting.totalProjects": "Всего проектов",
    "reporting.openOrders": "Открытые заказы",
    "reporting.productionOrders": "Производственные заказы",
    "reporting.workflowTasks": "Задачи рабочего процесса",
    "reporting.totalRecords": "Всего записей",
    "reporting.noData": "Данных пока нет",
    "reporting.noDataSub": "Добавьте данные в модули",
    "reporting.dataSummary": "Сводка данных модуля",
    "hr.title": "Кадры",
    "hr.employee": "Сотрудник",
    "hr.position": "Должность",
    "hr.department": "Отдел",
    "hr.status": "Статус",
    "hr.active": "Активный",
    "hr.onLeave": "В отпуске",
    "hr.terminated": "Уволен",
    "hr.addEmployee": "Добавить сотрудника",
    "hr.totalEmployees": "Всего сотрудников",
    "hr.searchEmployee": "Поиск сотрудника...",
    "accounting.title": "Бухгалтерия",
    "accounting.income": "Доходы",
    "accounting.expense": "Расходы",
    "accounting.balance": "Чистый баланс",
    "accounting.description": "Описание",
    "accounting.amount": "Сумма",
    "accounting.date": "Дата",
    "accounting.category": "Категория",
    "accounting.addTransaction": "Добавить транзакцию",
    "accounting.type": "Тип",
    "crm.title": "Отношения с клиентами",
    "crm.customer": "Клиент",
    "crm.lead": "Потенциальный",
    "crm.email": "Email",
    "crm.phone": "Телефон",
    "crm.status": "Статус",
    "crm.addCustomer": "Добавить клиента",
    "crm.lead_status": "Лид",
    "crm.active_status": "Активный",
    "crm.closed_status": "Закрытый",
    "inventory.title": "Склад",
    "inventory.product": "Продукт",
    "inventory.category": "Категория",
    "inventory.quantity": "Количество",
    "inventory.unitPrice": "Цена единицы",
    "inventory.totalValue": "Общая стоимость",
    "inventory.addProduct": "Добавить продукт",
    "inventory.lowStock": "Мало на складе",
    "projects.title": "Проекты",
    "projects.project": "Проект",
    "projects.status": "Статус",
    "projects.startDate": "Дата начала",
    "projects.endDate": "Дата окончания",
    "projects.team": "Участников",
    "projects.addProject": "Добавить проект",
    "projects.planning_status": "Планирование",
    "projects.active_status": "Активный",
    "projects.completed_status": "Завершён",
    "projects.paused_status": "На паузе",
    "projects.tasks": "Задачи",
    "settings.title": "Настройки компании",
    "supplier.title": "Поставщики",
    "supplier.add": "Добавить поставщика",
    "supplier.edit": "Редактировать поставщика",
    "supplier.name": "Название поставщика",
    "supplier.contact": "Контактное лицо",
    "supplier.phone": "Телефон",
    "supplier.email": "Эл. почта",
    "supplier.category": "Категория",
    "supplier.paymentTerms": "Условия оплаты",
    "supplier.rating": "Рейтинг",
    "supplier.notes": "Заметки",
    "supplier.totalSuppliers": "Всего поставщиков",
    "purchasing.tabs.orders": "Заказы",
    "purchasing.tabs.suppliers": "Поставщики",
    "profile.title": "Настройки профиля",
    "profile.displayName": "Полное имя",
    "profile.loginCode": "Код входа",
    "profile.personnelCode": "Код сотрудника",
    "profile.language": "Языковые предпочтения",
    "profile.save": "Сохранить",
    "profile.saved": "Сохранено",
    "profile.show": "Показать",
    "profile.hide": "Скрыть",
    "profile.copy": "Копировать",
    "profile.copied": "Скопировано",
    "nav.profile": "Профиль",
  },
  zh: {
    "landing.title": "ERPVerse",
    "landing.subtitle": "统一商业管理平台",
    "landing.description": "从单一平台管理您的公司",
    "portal.owner": "公司所有者",
    "portal.owner.desc": "设置或管理公司",
    "portal.manager": "公司经理",
    "portal.manager.desc": "访问经理面板",
    "portal.admin": "公司管理员",
    "portal.admin.desc": "访问管理员面板",
    "portal.employee": "公司员工",
    "portal.employee.desc": "访问员工面板",
    "auth.login": "登录",
    "auth.register": "注册",
    "auth.loginCode": "您的登录码",
    "auth.personnelCode": "您的员工码",
    "auth.fullName": "全名",
    "auth.enterCode": "输入您的代码",
    "auth.enterName": "输入您的姓名",
    "auth.submit": "继续",
    "auth.backToLogin": "登录",
    "auth.noCompany": "您尚未加入任何公司。",
    "code.title": "注册成功!",
    "code.subtitle": "请将以下代码保存在安全的地方。",
    "code.loginCode": "您的登录码",
    "code.personnelCode": "您的员工码",
    "code.copied": "已复制!",
    "code.copy": "复制",
    "code.continue": "登录",
    "company.setup.title": "公司设置",
    "company.setup.subtitle": "输入公司详细信息",
    "company.name": "公司名称",
    "company.sector": "行业",
    "company.address": "地址",
    "company.email": "联系邮箱",
    "company.phone": "电话",
    "company.foundedYear": "成立年份",
    "company.create": "创建公司",
    "company.select.title": "选择公司",
    "company.select.subtitle": "您想访问哪家公司?",
    "dashboard.overview": "概览",
    "dashboard.personnel": "人员管理",
    "dashboard.modules": "模块权限",
    "dashboard.settings": "设置",
    "dashboard.employees": "员工总数",
    "dashboard.activeModules": "活跃模块",
    "dashboard.company": "公司",
    "personnel.add": "添加人员",
    "personnel.code": "员工码",
    "personnel.role": "角色",
    "personnel.modules": "模块",
    "personnel.remove": "移除",
    "personnel.added": "人员添加成功",
    "personnel.removed": "人员已移除",
    "personnel.notFound": "未找到人员",
    "personnel.noMembers": "暂无人员",
    "role.owner": "所有者",
    "role.manager": "经理",
    "role.admin": "管理员",
    "role.employee": "员工",
    "modules.HR": "人力资源",
    "modules.Accounting": "会计",
    "modules.CRM": "CRM",
    "modules.Inventory": "库存",
    "modules.Projects": "项目",
    "modules.Purchasing": "采购",
    "modules.Production": "生产",
    "modules.Workflow": "工作流",
    "modules.Reporting": "报告",
    "nav.logout": "退出",
    "nav.back": "返回",
    "common.save": "保存",
    "common.cancel": "取消",
    "common.loading": "加载中...",
    "common.error": "发生错误",
    "common.success": "成功",
    "module.comingSoon": "此模块即将上线",
    "purchasing.title": "采购",
    "purchasing.supplier": "供应商",
    "purchasing.amount": "金额",
    "purchasing.date": "日期",
    "purchasing.status": "状态",
    "purchasing.addOrder": "添加订单",
    "purchasing.pending": "待处理",
    "purchasing.approved": "已批准",
    "purchasing.delivered": "已交付",
    "purchasing.totalOrders": "总订单数",
    "production.title": "生产",
    "production.product": "产品",
    "production.quantity": "数量",
    "production.progress": "进度",
    "production.status": "状态",
    "production.addOrder": "添加生产",
    "production.planned": "已计划",
    "production.inProgress": "进行中",
    "production.completed": "已完成",
    "workflow.title": "工作流",
    "workflow.task": "任务",
    "workflow.assignee": "负责人",
    "workflow.priority": "优先级",
    "workflow.status": "状态",
    "workflow.addTask": "添加任务",
    "workflow.high": "高",
    "workflow.medium": "中",
    "workflow.low": "低",
    "workflow.pending": "待处理",
    "workflow.inProgress": "进行中",
    "workflow.done": "完成",
    "reporting.title": "报告",
    "reporting.revenue": "收入",
    "reporting.expenses": "支出",
    "reporting.netProfit": "净利润",
    "reporting.employees": "员工",
    "reporting.monthlyChart": "月度图表",
    "reporting.moduleUsage": "模块使用率",
    "reporting.totalEmployees": "员工总数",
    "reporting.active": "活跃",
    "reporting.totalTransactions": "总交易数",
    "reporting.totalCustomers": "总客户数",
    "reporting.totalProducts": "总产品数",
    "reporting.totalProjects": "总项目数",
    "reporting.openOrders": "待处理订单",
    "reporting.productionOrders": "生产订单",
    "reporting.workflowTasks": "工作流任务",
    "reporting.totalRecords": "总记录数",
    "reporting.noData": "暂无数据",
    "reporting.noDataSub": "请向模块添加数据",
    "reporting.dataSummary": "模块数据摘要",
    "hr.title": "人力资源",
    "hr.employee": "员工",
    "hr.position": "职位",
    "hr.department": "部门",
    "hr.status": "状态",
    "hr.active": "在职",
    "hr.onLeave": "休假",
    "hr.terminated": "已离职",
    "hr.addEmployee": "添加员工",
    "hr.totalEmployees": "员工总数",
    "hr.searchEmployee": "搜索员工...",
    "accounting.title": "财务管理",
    "accounting.income": "收入",
    "accounting.expense": "支出",
    "accounting.balance": "净余额",
    "accounting.description": "描述",
    "accounting.amount": "金额",
    "accounting.date": "日期",
    "accounting.category": "类别",
    "accounting.addTransaction": "添加交易",
    "accounting.type": "类型",
    "crm.title": "客户关系",
    "crm.customer": "客户",
    "crm.lead": "潜在客户",
    "crm.email": "邮箱",
    "crm.phone": "电话",
    "crm.status": "状态",
    "crm.addCustomer": "添加客户",
    "crm.lead_status": "潜在",
    "crm.active_status": "活跃",
    "crm.closed_status": "已关闭",
    "inventory.title": "库存管理",
    "inventory.product": "产品",
    "inventory.category": "类别",
    "inventory.quantity": "数量",
    "inventory.unitPrice": "单价",
    "inventory.totalValue": "总价值",
    "inventory.addProduct": "添加产品",
    "inventory.lowStock": "库存不足",
    "projects.title": "项目管理",
    "projects.project": "项目",
    "projects.status": "状态",
    "projects.startDate": "开始日期",
    "projects.endDate": "结束日期",
    "projects.team": "成员",
    "projects.addProject": "添加项目",
    "projects.planning_status": "规划中",
    "projects.active_status": "进行中",
    "projects.completed_status": "已完成",
    "projects.paused_status": "已暂停",
    "projects.tasks": "任务",
    "settings.title": "公司设置",
    "supplier.title": "供应商",
    "supplier.add": "添加供应商",
    "supplier.edit": "编辑供应商",
    "supplier.name": "供应商名称",
    "supplier.contact": "联系人",
    "supplier.phone": "电话",
    "supplier.email": "电子邮件",
    "supplier.category": "类别",
    "supplier.paymentTerms": "付款条件",
    "supplier.rating": "评分",
    "supplier.notes": "备注",
    "supplier.totalSuppliers": "供应商总数",
    "purchasing.tabs.orders": "订单",
    "purchasing.tabs.suppliers": "供应商",
    "profile.title": "个人设置",
    "profile.displayName": "全名",
    "profile.loginCode": "登录码",
    "profile.personnelCode": "员工代码",
    "profile.language": "语言偏好",
    "profile.save": "保存",
    "profile.saved": "已保存",
    "profile.show": "显示",
    "profile.hide": "隐藏",
    "profile.copy": "复制",
    "profile.copied": "已复制",
    "nav.profile": "个人资料",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (l: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "tr",
  setLanguage: () => {},
  t: (key) => key,
  isRTL: false,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem("erpverse_lang") as Language) || "tr";
  });

  const setLanguage = (l: Language) => {
    setLanguageState(l);
    localStorage.setItem("erpverse_lang", l);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  const isRTL = language === "ar";

  useEffect(() => {
    document.documentElement.setAttribute("dir", isRTL ? "rtl" : "ltr");
  }, [isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: "tr", label: "Türkçe", flag: "🇹🇷" },
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "de", label: "Deutsch", flag: "🇩🇪" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "es", label: "Español", flag: "🇪🇸" },
  { code: "ar", label: "العربية", flag: "🇸🇦" },
  { code: "ru", label: "Русский", flag: "🇷🇺" },
  { code: "zh", label: "中文", flag: "🇨🇳" },
];
